# Generated by Django 5.1.3 on 2024-12-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.TextField()),
                ('registrar_name', models.TextField()),
                ('expiry_date', models.TextField()),
            ],
            options={
                'db_table': 'domains',
            },
        ),
    ]
